name: Deploy FastAPI to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        cd backend
        docker build -t asia-south1-docker.pkg.dev/tutor-app-460518/tutor-app-dibbo/backend-api:$GITHUB_SHA .
        docker push asia-south1-docker.pkg.dev/tutor-app-460518/tutor-app-dibbo/backend-api:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy tutor-app-backend \
          --image asia-south1-docker.pkg.dev/tutor-app-460518/tutor-app-dibbo/backend-api:$GITHUB_SHA \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated \
          --port 8080
